apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-dogukan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-dogukan
  template:
    metadata:
      labels:
        app: hello-world-dogukan
    spec:
      containers:
      - name: hello-world-dogukan
        image: bolbi85/hello-world-dogukan:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-dogukan
spec:
  selector:
    app: hello-world-dogukan
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
